global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'oncall-web'
    static_configs:
      - targets:
        - oncall-web:8081