server:
  host: 0.0.0.0
  port: 8080
debug: True
oncall_host: http://localhost:8080
metrics: dummy
db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: root
      host: 127.0.0.1
      database: oncall
      charset: utf8
      echo: True
    str: "%(scheme)s://%(user)s@%(host)s/%(database)s?charset=%(charset)s"
  kwargs:
    pool_recycle: 3600
session:
  encrypt_key: 'abc'
  sign_key: '123'
auth:
  debug: True
  module: 'oncall.auth.modules.debug'
#   module: 'oncall.auth.modules.ldap_example'
#   ldap_url: 'ldaps://example.com'
#   ldap_user_suffix: '@example.biz'
#   ldap_cert_path: '/etc/ldap_cert.pem'
#   if you need to lookup the DN of the user first
#   ldap_bind_user: 'cn=binduser,ou=services,dc=company,dc=org'
#   ldap_bind_password: 'abc123'
#   ldap_base_dn: 'ou=accounts,dc=company,dc=org'
#   ldap_search_filter: '(uid=%s)'
notifier:
  skipsend: True
healthcheck_path: /tmp/status
messengers:
#   - type: rocketchat_messenger
#     user: username
#     password: abc123
#     refresh: 60000
#     api_host: https://example.rocket.chat
  - type: dummy
    application: oncall
    iris_api_key: magic

## To run Oncall without https, set this value to True
## WARNING: use this only for debugging purposes, to avoid sending
## usernames and passwords in plain text.
#allow_http: False

# allow_origins_list:
#   - http://www.example.com

supported_timezones:
  - 'US/Pacific'
  - 'US/Eastern'
  - 'US/Central'
  - 'US/Mountain'
  - 'US/Alaska'
  - 'US/Hawaii'
  - 'Asia/Kolkata'
  - 'Asia/Shanghai'
  - 'UTC'

index_content_setting:
  footer: |
    <ul>
      <li>Oncall Â© LinkedIn 2017</li>
      <li>Feedback</li>
      <li><a href="http://oncall.tools" target="_blank">About</a></li>
    </ul>
  missing_number_note: 'No number'

notifications:
  default_roles:
    - "primary"
    - "secondary"
    - "shadow"
    - "manager"
  default_times:
    - 86400
    - 604800
  default_modes:
    - "email"

reminder:
  activated: True
  polling_interval: 360
  default_timezone: 'US/Pacific'

user_validator:
  activated: True
  subject: 'Warning: Missing phone number in Oncall'
  body: 'You are scheduled for an on-call shift in the future, but have no phone number recorded. Please update your information in Oncall.'

slack_instance: foobar
header_color: '#3a3a3a'
iris_plan_integration:
  activated: True
  app: oncall
  api_key: magic
  api_host: http://localhost:16649
  plan_url: '/v0/applications/oncall/plans'
  urgent_plan:
    name: 'Oncall Urgent'
    dynamic_targets:
      - role: 'oncall-primary'
      - role: 'team'
      - role: 'manager'
  medium_plan:
    name: 'Oncall Medium'
    dynamic_targets:
      - role: 'oncall-primary'
      - role: 'team'
      - role: 'manager'


# slack:
#   oauth_access_token: 'foo'
#
# user_sync:
#   module: 'oncall.user_sync.ldap_sync'
# ldap_sync:
#   url: 'ldaps://example.com'
#   base: 'ou=Staff Users,dc=multiforest,dc=biz'
#   user: 'CN=example,DC=multiforest,DC=biz'
#   password: 'password'
#   cert_path: '/etc/ldap_cert.pem'
#   query: '(&(objectClass=userProxy)(employeeId=*))'
#   attrs:
#     username: 'sAMAccountName'
#     full_name: 'displayName'
#     mail: 'mail'
#     mobile: 'mobile'
#   image_url: 'https://image.example.com/api/%s/picture'
